//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointments
    {
        public int appointment_id { get; set; }
        public int patient_id { get; set; }
        public int doctor_id { get; set; }
        public System.DateTime appointment_date { get; set; }
        public string reason { get; set; }
        public int status_id { get; set; }
    
        public virtual doctors doctors { get; set; }
        public virtual patients patients { get; set; }
        public virtual statuses statuses { get; set; }
    }
}
