//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class medical_records
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medical_records()
        {
            this.prescriptions = new HashSet<prescriptions>();
        }
    
        public int record_id { get; set; }
        public int patient_id { get; set; }
        public int doctor_id { get; set; }
        public System.DateTime visit_date { get; set; }
        public string diagnosis { get; set; }
        public string treatment { get; set; }
        public string notes { get; set; }
    
        public virtual doctors doctors { get; set; }
        public virtual patients patients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prescriptions> prescriptions { get; set; }
    }
}
