//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic
{
    using System;
    using System.Collections.Generic;
    
    public partial class prescriptions
    {
        public int prescription_id { get; set; }
        public int record_id { get; set; }
        public int drug_id { get; set; }
        public string description { get; set; }
    
        public virtual drugs drugs { get; set; }
        public virtual medical_records medical_records { get; set; }
    }
}
